[package]
name = "AoC24"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day1b"
path = "src/day1b.rs"
[[bin]]
name = "day2b"
path = "src/day2b.rs"